version: '3'

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: planet-database
    tty: true
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=planet-user
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "5566:8080"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
volumes:
  postgres_data: